name: Auto Build

on:
  push:
#    branches:
#      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: update submodule
      run: |
        git submodule update --init --recursive
        mv -f Dockerfile ${GITHUB_WORKSPACE}/leavexchat-bot
        cd ${GITHUB_WORKSPACE}/leavexchat-bot

    - name: build and push image
      uses: docker/build-push-action@v1

      with:
        file: ${GITHUB_WORKSPACE}/leavexchat-bot/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: artxia/leavexchat-bot-docker
        tags: latest
