name: Auto Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1

      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: artxia/leavexchat-bot-docker
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
